# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('steam_id', models.CharField(max_length=20)),
                ('team_choices', models.CharField(choices=[('DUOS', 'DUOS'), ('SQUADS', 'SQUADS'), ('DUOS FPS', 'DUOS FPS'), ('SQUADS FPS', 'SQUADS FPS')], max_length=10, verbose_name='team preference')),
                ('region_choices', models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('AS', 'Asian'), ('OC', 'Oceania'), ('SA', 'South America'), ('SEA', 'South East Asia'), ('KR/JP', 'Korea/Japan')], max_length=5, verbose_name='region preference')),
                ('email', models.CharField(max_length=40)),
                ('has_profile', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
        ),
    ]
